### ISSUE TITLE
Purchase of new domains

### ISSUE THREAD

**Issue by MerseyHubGroup-BM** [MerseyAnimalHub/Website#4]
We will be buying new domains for this release. Domains will be announced when we have created them.

- [x] Creation of Domain Names.
- [x] Setup of Domains Name Servers.
- [x] Wait for propagation.

**Comment by MerseyAnimalHub-BM** [comment]
### New Domains

- https://www.m-a-h.org.uk
- https://www.merseyanimalrescue.org.uk
